version: "3"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/src
    links:
      - mongodb
  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=interview-nodejs-db